name: Release
on:
  push:
    branches:
      - main
jobs:
  validate:
    uses: ./.github/workflows/validate.yaml

  release:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install --package-lock=false
      - run: npm run version:bump -- --yes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      - run: npm run version:release -- --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
